export function mapApplicationRow(row: Record<string, unknown>) {
  return {
    id: row.id as string,
    userId: row.user_id as string,
    firstName: (row.first_name as string) ?? '',
    lastName: (row.last_name as string) ?? '',
    email: (row.email as string) ?? '',
    phone: (row.phone as string) ?? '',
    status: row.status as 'pending' | 'approved' | 'rejected',
    submittedAt: row.submitted_at as string,
    rejectionReason: (row.rejection_reason as string | null) ?? undefined,
    applicationType: row.applicationType as 'driver' | 'restaurant',
    incompleteSignup: Boolean(row.incompleteSignup),
    vehicleType: (row.vehicle_type as string | null) ?? undefined,
    vehicleMake: (row.vehicle_make as string | null) ?? undefined,
    vehicleModel: (row.vehicle_model as string | null) ?? undefined,
    vehicleYear: row.vehicle_year != null ? Number(row.vehicle_year) : undefined,
    vehicleReg: (row.vehicle_reg as string | null) ?? undefined,
    idNumber: (row.id_number as string | null) ?? undefined,
    dateOfBirth: row.date_of_birth != null ? String(row.date_of_birth) : undefined,
    bankName: (row.bank_name as string | null) ?? undefined,
    bankAccountNo: (row.bank_account_no as string | null) ?? undefined,
    bankHolder: (row.bank_holder as string | null) ?? undefined,
    bankBranch: (row.bank_branch as string | null) ?? undefined,
    idDocumentUrl: (row.id_document_url as string | null) ?? undefined,
    driversLicenseUrl: (row.drivers_license_url as string | null) ?? undefined,
    vehicleRegistrationUrl: (row.vehicle_registration_url as string | null) ?? undefined,
    tradingName: (row.trading_name as string | null) ?? undefined,
    businessRegNo: (row.business_reg_no as string | null) ?? undefined,
    cuisineType: (row.cuisine_type as string | null) ?? undefined,
    address: (row.address as string | null) ?? undefined,
    city: (row.city as string | null) ?? undefined,
    description: (row.description as string | null) ?? undefined,
    businessDocUrl: (row.business_doc_url as string | null) ?? undefined,
  };
}
